"""add procedures dictionary

Revision ID: 39ed9e8781cd
Revises: 6fd42c884acb
Create Date: 2026-04-25 14:32:25.522690

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39ed9e8781cd"
down_revision: Union[str, Sequence[str], None] = "6fd42c884acb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "procedures",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("default_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index("idx_procedures_category", "procedures", ["category"])
    op.create_index("idx_procedures_code", "procedures", ["code"])
    op.create_index("idx_procedures_name", "procedures", ["name"])
    op.create_table(
        "medical_record_procedures",
        sa.Column("medical_record_id", sa.String(), nullable=False),
        sa.Column("procedure_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medical_record_id"], ["medical_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["procedure_id"], ["procedures.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("medical_record_id", "procedure_id"),
    )
    # ### end Alembic commands ###

    # Backfill old free-text procedure values into the new dictionary.
    # Each distinct legacy string becomes one active procedure in the
    # "Legacy" category so existing medical records keep their procedure data.
    # The generated IDs/codes are deterministic, which keeps the association
    # backfill below stable if the migration is inspected or replayed.
    op.execute("""
        INSERT INTO procedures (
            id,
            code,
            name,
            category,
            description,
            default_price,
            is_active,
            created_at,
            updated_at
        )
        SELECT
            'legacy-' || md5(procedures),
            'LEGACY-' || upper(substr(md5(procedures), 1, 12)),
            procedures,
            'Legacy',
            NULL,
            0,
            TRUE,
            now(),
            now()
        FROM (
            SELECT DISTINCT procedures
            FROM medical_records
            WHERE procedures IS NOT NULL AND procedures <> ''
        ) AS legacy_procedures
        """)
    # Link each existing medical record to the dictionary procedure created
    # from its previous `medical_records.procedures` string before dropping the
    # old column. Blank legacy values are ignored because the old column was
    # intended to hold meaningful procedure text.
    op.execute("""
        INSERT INTO medical_record_procedures (medical_record_id, procedure_id)
        SELECT
            id,
            'legacy-' || md5(procedures)
        FROM medical_records
        WHERE procedures IS NOT NULL AND procedures <> ''
        """)
    op.drop_column("medical_records", "procedures")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "medical_records",
        sa.Column("procedures", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # Downgrade has to flatten a many-to-many list back into the old string
    # column. Multiple procedures are joined by name for a readable fallback;
    # exact list structure cannot be represented in the previous schema.
    op.execute("""
        UPDATE medical_records
        SET procedures = selected_procedures.procedure_names
        FROM (
            SELECT
                medical_record_procedures.medical_record_id,
                string_agg(
                    procedures.name,
                    ', '
                    ORDER BY procedures.name
                ) AS procedure_names
            FROM medical_record_procedures
            JOIN procedures
                ON procedures.id = medical_record_procedures.procedure_id
            GROUP BY medical_record_procedures.medical_record_id
        ) AS selected_procedures
        WHERE medical_records.id = selected_procedures.medical_record_id
        """)
    op.execute("UPDATE medical_records SET procedures = '' WHERE procedures IS NULL")
    op.alter_column("medical_records", "procedures", nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medical_record_procedures")
    op.drop_index("idx_procedures_name", table_name="procedures")
    op.drop_index("idx_procedures_code", table_name="procedures")
    op.drop_index("idx_procedures_category", table_name="procedures")
    op.drop_table("procedures")
    # ### end Alembic commands ###
