"""add procedure categories dictionary

Revision ID: 5d085590d409
Revises: 39ed9e8781cd
Create Date: 2026-04-25 14:46:07.069839

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d085590d409"
down_revision: Union[str, Sequence[str], None] = "39ed9e8781cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "procedure_categories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "idx_procedure_categories_code",
        "procedure_categories",
        ["code"],
    )
    op.create_index(
        "idx_procedure_categories_name",
        "procedure_categories",
        ["name"],
    )
    op.add_column(
        "procedures",
        sa.Column("category_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO procedure_categories (
            id,
            code,
            name,
            description,
            is_active,
            created_at,
            updated_at
        )
        SELECT
            'legacy-category-' || md5(category),
            'LEGACY-CAT-' || upper(substr(md5(category), 1, 8)),
            category,
            NULL,
            TRUE,
            now(),
            now()
        FROM (
            SELECT DISTINCT category
            FROM procedures
            WHERE category IS NOT NULL AND category <> ''
        ) AS legacy_categories
        """)
    op.execute("""
        UPDATE procedures
        SET category_id = 'legacy-category-' || md5(category)
        WHERE category IS NOT NULL AND category <> ''
        """)
    op.execute("""
        INSERT INTO procedure_categories (
            id,
            code,
            name,
            description,
            is_active,
            created_at,
            updated_at
        )
        SELECT
            'legacy-category-uncategorized',
            'UNCATEGORIZED',
            'Uncategorized',
            NULL,
            TRUE,
            now(),
            now()
        WHERE EXISTS (
            SELECT 1
            FROM procedures
            WHERE category_id IS NULL
        )
        """)
    op.execute("""
        UPDATE procedures
        SET category_id = 'legacy-category-uncategorized'
        WHERE category_id IS NULL
        """)

    op.alter_column("procedures", "category_id", nullable=False)
    op.drop_index(op.f("idx_procedures_category"), table_name="procedures")
    op.create_index("idx_procedures_category_id", "procedures", ["category_id"])
    op.create_foreign_key(
        "fk_procedures_category_id_procedure_categories",
        "procedures",
        "procedure_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_column("procedures", "category")


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column(
        "procedures",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.execute("""
        UPDATE procedures
        SET category = procedure_categories.name
        FROM procedure_categories
        WHERE procedures.category_id = procedure_categories.id
        """)
    op.execute("UPDATE procedures SET category = '' WHERE category IS NULL")
    op.alter_column("procedures", "category", nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_procedures_category_id_procedure_categories",
        "procedures",
        type_="foreignkey",
    )
    op.drop_index("idx_procedures_category_id", table_name="procedures")
    op.create_index(
        op.f("idx_procedures_category"),
        "procedures",
        ["category"],
    )
    op.drop_column("procedures", "category_id")
    op.drop_index(
        "idx_procedure_categories_name",
        table_name="procedure_categories",
    )
    op.drop_index(
        "idx_procedure_categories_code",
        table_name="procedure_categories",
    )
    op.drop_table("procedure_categories")
    # ### end Alembic commands ###
