"""add users table.

Revision ID: f4cb16d8bb59
Revises:
Create Date: 2026-01-02 12:35:11.132167

"""

from typing import Sequence, Union

from ulid import ULID

from alembic import op
import sqlalchemy as sa
from datetime import datetime

from clinic_registry.settings import Settings
from clinic_registry.core.enums.user import UserRole
from clinic_registry.core.helpers.auth import AuthHelper

# revision identifiers, used by Alembic.
revision: str = "f4cb16d8bb59"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

app_settings = Settings()  # type: ignore

ROOT_USER_LOGIN = "root"
ROOT_USER_PASSWORD = "root"
ROOT_USER_EMAIL = ("root@clinic.local",)
ROOT_USER_FIRST_NAME = ("Root",)
ROOT_USER_LAST_NAME = ("User",)


def upgrade() -> None:
    auth_helper = AuthHelper(
        secret_key=app_settings.jwt_secret_key,
        hashing_algorithm=app_settings.jwt_hashing_algorithm,
    )

    users_table = op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )

    now = datetime.now()

    op.bulk_insert(
        users_table,
        [
            {
                "id": str(ULID()),
                "username": ROOT_USER_LOGIN,
                "first_name": ROOT_USER_FIRST_NAME,
                "last_name": ROOT_USER_LAST_NAME,
                "email": ROOT_USER_EMAIL,
                "role": UserRole.admin,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
                "password_hash": auth_helper.hash_password(ROOT_USER_PASSWORD),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
